exclude_dirs:
  - noxfile.py
assert_used:
  skips:
    - ./**/test_*.py
    - ./tests/**
skips:
  - B102 # exec_used - intentional for Pydantic model import
  - B202 # tarfile.extractall - used in temp directory with user-provided archives
  - B324 # hashlib - MD5 used for stable doc ID generation, not security
